### ISSUE TITLE
Setup Recipe App Kanban Board

### ISSUE THREAD

**Issue by aliatayee** [aliatayee/recipe-app#25]
## Setup Recipe App Kanban Board
[Project Link](https://github.com/users/aliatayee/projects/2)
We are two members for this project

**Comment by AmaduKamara** [comment]
# Status: Approved 🟢🟢🟢 

Hi Team,

Your project is complete!  

There is nothing else to say other than... it's time to get started on the real development process 💪💪💪 Good luck
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
